//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunAndChhiroWebApi.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreTableInfo
    {
        public System.Guid Oid { get; set; }
        public System.Guid CreatedOid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedOid { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual File File { get; set; }
        public virtual User User { get; set; }
    }
}
