//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunAndChhiroWebApi.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public System.Guid FolderOid { get; set; }
        public string Name { get; set; }
    
        public virtual CoreTableInfo CoreTableInfo { get; set; }
    }
}
