//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JunAndChhiroWebApi.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUser
    {
        public System.Guid UserOid { get; set; }
        public string Id { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid CreatedOid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedOid { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
